<?php
	/*framework: get current theme setting*/
	$list_image_width = (int)$this->getConfig("image_width", 300);
	$list_image_height = (int)$this->getConfig("image_height", 300);
	$swap_image_number = (int)$this->getConfig("swap_image_number", 0);

	$popup_quickview_width = $this->getConfig("popup_quickview_width", "60%");
	$popup_quickview_height = $this->getConfig("popup_quickview_height", "80%");

	/*end get setting*/

	/*quickview was enabled?*/
	$quickview = $this->getConfig('enable_quickview', 0);
	/*Swap images was enabled?*/
	$swap_image = $this->getConfig('enable_swap', 0);

	$tabs = array( "news"		=> $this->__('New Arrival '),
				   "featured"	=> $this->__("Featured"),
				   "specical"	=> $this->__("Special"),
				   "bestseller"	=> $this->__("Best Seller"),
				   "mostview"	=> $this->__("Most Viewed")
	);
	$current = 0;
	$cols = (int)$this->getConfig("itemsrow",4);
	$itemsperpage = (int)$this->getConfig("itemspage",4);
	$desc_maxchar = (int)$this->getConfig("desc_maxchar");
	$desc_maxchar = $desc_maxchar > 0 ?$desc_maxchar: 100;
	$span = floor(12/$cols);
	$active = 'news';
	$modid = rand(1,9)+rand();
?>
<?php $_helper = $this->helper('catalog/output'); ?>

<div class="<?php echo $this->getConfig('prefix');?> block producttabs">
<?php if($this->getConfig('title')) { ?>
	<div class="block-title">
		<h2><?php echo $this->getConfig('title') ?></h2>
		<?php if( ($pretext=$this->getConfig("pretext")) && !$cms ) { ?>
			<div class="pretext"><?php echo $pretext; ?></div>
		<?php } else {
			?>
			<div class="pretext"><?php echo $cms; ?></div>
			<?php
		} ?>
	</div>
	<?php } ?>
  <div class="tab-nav">
	<ul class="nav nav-tabs" id="producttabs<?php echo $modid;?>">
		<?php foreach( $tabs as $key => $value ) { ?>
			<?php if( isset($$key) && !empty($$key) ) {     $products = $$key; ?>
			<?php if( empty($products) || $products->getSize() <= 0){ continue; } ?>
			 <li class="tab-<?php echo $key;?>"><a href="#tab-<?php echo $key.$modid;?>" data-toggle="tab"><?php echo $value; ?></a></li>
		<?php } ?>
		<?php } ?>
	</ul>
  </div>
<div class="tab-content">
		<?php $i=0; foreach( $tabs as $tab => $text ) { ?>
			<?php if( isset($$tab) && !empty($$tab) ) {     $products = $$tab; ?>
			<?php if( empty($products) || $products->getSize() <= 0){ continue; } ?>
			<?php $products = $products->getItems(); ?>
			<div class="tab-pane box-products  tabcarousel<?php echo $modid; ?> slide" id="tab-<?php echo $tab.$modid;?>">
				
				<?php if( count($products) > $itemsperpage ) { ?>
				<div class="carousel-controls">
				<a class="carousel-control left" href="#tab-<?php echo $tab.$modid;?>"   data-slide="prev">&lsaquo;</a>
				<a class="carousel-control right" href="#tab-<?php echo $tab.$modid;?>"  data-slide="next">&rsaquo;</a>
				</div>
				<?php } ?>
				<div class="carousel-inner ">		
				 <?php 
					$pages = array_chunk( $products, $itemsperpage);
				 ?>	
				  <?php foreach ($pages as  $k => $tproducts ) {  ?>
						<div class="item <?php if($k==0) {?>active<?php } ?>">
							<?php foreach( $tproducts as $i => $_product ) {  $i=$i+1;?>
								<?php if( $i%$cols == 1 ) { ?>
								  <div class="row box-product">
								<?php } ?>
									  <div class="col-lg-<?php echo $span;?> col-sm-<?php echo $span;?> col-xs-12 product-block"><div class="product-inner">
									  	<?php
				                            $swap_class = "";
				                            if($swap_image && $hover_image = Mage::helper("ves_tempcp/framework")->getProductImage($_product->getId(), $swap_image_number , $list_image_width, $list_image_height)) {
				                                    $swap_class = "swap";
				                             } 
				                    	?>
										<div class="image <?php echo $swap_class; ?> product-image image-thumb"><a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">

											<?php 
											if($this->getConfig("enable_sale_icon")) {
				                                // Get the Special Price
				                                $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
				                                // Get the Special Price FROM date
				                                $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
				                                // Get the Special Price TO date
				                                $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
				                                // Get Current date
				                                $today =  time();
				                             
				                                if ($specialprice) {
				                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
			                            ?>
			                                    <span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
			                            <?php  
			                                   	 }
			                                	}
			                           		}
			                            ?>
			                            	<?php
			                            	if($this->getConfig("enable_new_icon")) {
				                                $is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );
				                                
				                                if($is_new) { ?>
				                                <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
				                                <?php

				                                }
				                            }
				                            ?>

											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($list_image_width, $list_image_height) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
											</a>
											<?php if($swap_class) { ?>
			                                <span class="hover-image">
			                                    <a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"></a>
			                                </span>
			                            	<?php } ?>
											<?php if( $this->getConfig("show_pzoom") ) { ?>
											<?php
					                            $productId = $_product->getId();
					                            $_product = Mage::getModel('catalog/product')->load($productId);
					                        ?>
					                        <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(800);?>" class="colorbox product-zoom cboxElement" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><i class="icon-zoom-in"></i></a>
												<?php } ?>
										</div>
										<?php if( $this->getConfig('show_title',1) ) { ?>
											<div class="name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></div>
										<?php } ?>	

										<?php if ( $this->getConfig('show_des') ) { ?>
											<div class="description">
												<?php
														$product_short_desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
														echo $this->subString($product_short_desc, $desc_maxchar, "");
													 ?>

											</div>
										<?php } ?>

										<?php if ( $this->getConfig('review',1) ) { ?>
											<div class="review"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div>
										<?php } ?>

									

										<?php if($this->getConfig('show_price',1)) { ?>
										<?php echo $this->getPriceHtml($_product, true); ?>
										<?php } ?>

										<?php if( $this->getConfig("enable_wc", 0) ) { ?>		
										<!-- Add to links -->
										<ul class="add-to-links">
											<?php if ($this->helper('wishlist')->isAllow()) : ?>
												<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
											<?php endif; ?>
											<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
												<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
											<?php endif; ?>
										</ul>
										<?php } ?>

										<?php if ($this->getConfig('show_btn',1) ) { ?>
											<div class="actions">
												<?php if($_product->isSaleable()) { ?>
												<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
												<?php } else { ?>
												<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
												<?php } ?>
												<?php if ($this->getConfig('detail') ) { ?>
												<button type="button" title="<?php echo $this->__('Detail') ?>" class="button btn-detail" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('Detail') ?></span></span></button>
												<?php } ?>
											</div>
										<?php } ?>
										<?php if ($quickview) { ?>
						                        <a class="ves-tabshome-colorbox<?php echo $modid;?> ves-quickview" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>"><span class='fa fa-plus'></span><?php echo $this->__('Quick View'); ?></a>
						                <?php } ?>
									  </div></div>
							  
							  <?php if( $cols == 1 || $i%$cols == 0 || $i==count($tproducts) ) { ?>
								 </div>
								<?php } ?>
							<?php } ?>
						</div>
				  <?php } ?>
				</div>
			</div>
		<?php } // End of if ?>
		<?php } // endforeach of tabs?>

</div>
</div>
<?php if( $this->getConfig("show_pzoom") ) {  ?>
<script type="text/javascript">
<!--
jQuery(document).ready(function() {
	if(typeof(colorbox) != "undefined"){
		jQuery('.colorbox').colorbox({
			overlayClose: true,
			opacity: 0.5,
			rel: false,
			onLoad:function(){
				jQuery("#cboxNext").remove(0);
				jQuery("#cboxPrevious").remove(0);
				jQuery("#cboxCurrent").remove(0);
			}
		});
	} 
});
//-->
</script>
<?php } ?>
<script type="text/javascript">
<!--
jQuery(function () {
	jQuery('#producttabs<?php echo $modid;?> a:first').tab('show');
})
jQuery('.tabcarousel<?php echo $modid;?>').carousel({interval:false,auto:false,pause:'hover'});
//--></script>

<?php if ($quickview) { ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".ves-tabshome-colorbox<?php echo $modid;?>").colorbox({
                width: '<?php echo $popup_quickview_width; ?>', 
                height: '<?php echo $popup_quickview_height; ?>',
                overlayClose: true,
                opacity: 0.5,
                iframe: true, 
        });
        
    });
</script>
<?php } ?>