<?php 
 /*------------------------------------------------------------------------
  # VenusTheme Brand Module 
  # ------------------------------------------------------------------------
  # author:    VenusTheme.Com
  # copyright: Copyright (C) 2012 http://www.venustheme.com. All Rights Reserved.
  # @license: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
  # Websites: http://www.venustheme.com
  # Technical Support:  http://www.venustheme.com/
-------------------------------------------------------------------------*/
?>
<div class="ves-brandlist-page">
	<h1><?php echo $this->__( "All Brands" );?></h1>

	<div class="brand-wrapper vesclear">
		<ul>
		<?php $brands = $this->getBrands(); ?>
		<?php foreach( $brands as $brand ): ?>
			<li>
				<a href="<?php echo $brand->getLink();?>" title="<?php echo $brand->getTitle();?>">
				<img src="<?php echo $brand->getIconUrl();?>" alt="<?php echo $brand->getTitle();?>" />
				</a>
				<a href="<?php echo $brand->getLink();?>" title="<?php echo $brand->getTitle();?>">
					<span><?php echo $brand->getTitle();?></span>
				</a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>	
</div>