<?php 
 /*------------------------------------------------------------------------
  # Ves Blog Module 
  # ------------------------------------------------------------------------
  # author:    Ves.Com
  # copyright: Copyright (C) 2012 http://www.ves.com. All Rights Reserved.
  # @license: http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
  # Websites: http://www.ves.com
  # Technical Support:  http://www.ves.com/
-------------------------------------------------------------------------*/
?>
<div class="social-sharing vesclear">	
	<div class="social-label"><?php echo $this->__( "Share This:" ); ?></div>
	<?php if( $this->getGeneralConfig("twusername") ): ?>
	<!-- Twitter Button -->
	<div class="itemTwitterButton">
		<a href="https://twitter.com/share" class="twitter-share-button" 
		data-count="horizontal"<?php if($this->item->params->get('twitterUsername')): ?> 
		data-via="<?php echo $this->item->params->get('twitterUsername'); ?>"<?php endif; ?>>
			<?php echo JText::_('K2_TWEET'); ?>
		</a>
		<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
	</div>
	<?php endif; ?>
	<!-- Facebook Button -->
	<div class="facebook-button social-button">
		<div id="fb-root"></div>
		<script type="text/javascript">
			(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));
		</script>
		<div class="fb-like" data-send="false" data-width="200" data-show-faces="true"></div>
	</div>


	<!-- Google +1 Button -->
	<div class="itemGooglePlusOneButton">
		<g:plusone annotation="inline" width="120"></g:plusone>
		<script type="text/javascript">
		  (function() {
			window.___gcfg = {lang: 'en'}; // Define button default language here
			var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
			po.src = 'https://apis.google.com/js/plusone.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>
	</div>

</div>