<?php 
	$modid=rand();
?>
<div class="venus-blog-menu block">
	 <div class="block-title">
        <strong>
            <span><?php echo $this->__('Blog Categories') ?></span>
        </strong>
    </div>
	<div class="block-content">
	<?php if( count($menus) ): ?>
		<ul id="blog-menu<?php echo $modid; ?>">
		<?php foreach( $menus as $menu ): ?>
			<?php echo $this->renderTree( $menu , 1);	?>
		<?php endforeach; ?>
		
		</ul>
		<script type="text/javascript">
					$jmenu(document).ready(function(){	
						// applying the settings
						$jmenu("#blog-menu<?php echo $modid; ?> li.active span.head").addClass("selected");
						$jmenu('#blog-menu<?php echo $modid; ?>').Accordion({
							active: 'span.selected',
							header: 'span.head',
							alwaysOpen: false,
							animated: true,
							showSpeed: 400,
							hideSpeed: 800,
							event: 'click'
						});
					});	
				</script>
	<?php endif; ?>
	</div>
</div>