<?php
	/*framework: get current theme setting*/
	$list_image_width = (int)$this->getEffectConfig("image_width", 300);
	$list_image_height = (int)$this->getEffectConfig("image_height", 300);
	$swap_image_number = (int)$this->getEffectConfig("swap_image_number", 0);

	$popup_quickview_width = $this->getEffectConfig("popup_quickview_width", "60%");
	$popup_quickview_height = $this->getEffectConfig("popup_quickview_height", "80%");


	/*end get setting*/

	/*quickview was enabled?*/
	$quickview = $this->getConfig('enable_quickview');
	$quickview = $quickview ? $quickview : 0;
	/*Swap images was enabled?*/
	$swap_image = $this->getConfig('enable_swap');
	$swap_image = $swap_image ? $swap_image : 0;

	$moduleId = rand().time();
	$itemsperpage = (int)$this->getEffectConfig("max_items");
	$auto_play_mode = (int)$this->getEffectConfig("auto_play");

	$title_maxchar = (int)$this->getEffectConfig("titleMaxchar");
	$title_maxchar = $title_maxchar > 0 ?$title_maxchar: 100;
	$desc_maxchar = (int)$this->getEffectConfig("descMaxchar");
	$desc_maxchar = $desc_maxchar > 0 ?$desc_maxchar: 100;
	$interval = (int)$this->getEffectConfig("interval");

	$auto_play = $auto_play_mode?"true":"false";
	$cols = (int)$this->getEffectConfig("limit_cols");
	$cols = !empty($cols)?$cols:1;
	$span = 12/$cols;
	$active = 'latest';

	if($items){
		$items = $items->getItems();
	}

?>
<?php $_helper = $this->helper('catalog/output'); ?>
<div class="<?php echo $this->getConfig('prefix');?> block productcarousel" id="module<?php echo $moduleId; ?>">
	<?php if($this->getConfig('title')){?>
	<div class="block-title">
		<h2><?php echo $this->getConfig('title')?></h2>
		<?php if( ($pretext=$this->getConfig("pretext")) && !$cms ) { ?>
			<div class="pretext"><?php echo $pretext;?></div>
		<?php } else {
			?>
			<div class="pretext"><?php echo $cms;?></div>
			<?php
		} ?>
	</div>
	<?php }?>
	<div class="block-content">
		<div class="box-products carousel slide" id="productcarousel<?php echo $moduleId;?>">
			<?php if( count($items) > $itemsperpage && $this->getConfig("show_navigator")) { ?>
			<div class="carousel-controls">
				<a class="carousel-control left fa fa-angle-left" href="#productcarousel<?php echo $moduleId;?>"   data-slide="prev">&lt;</a>
				<a class="carousel-control right fa fa-angle-right" href="#productcarousel<?php echo $moduleId;?>"  data-slide="next">&gt;</a>
			</div>
			<?php } ?>
			<div class="carousel-inner">		
			<?php
			$pages = array_chunk( $items, $itemsperpage);
			?>
			<?php foreach ($pages as  $k => $tproducts ) {   ?>
					<div class="item <?php if($k==0) {?>active<?php } ?> product-grid no-margin">
						<?php foreach( $tproducts as $i => $_product ) {  $i=$i+1;?>
						<?php if( $cols == 1 || $i%$cols == 1 ) { ?>
						<div class="row">
						<?php } ?>
							<div class="col-lg-<?php echo $span;?> col-sm-<?php echo $span;?> col-xs-12">
								<div class="product-block">
									<?php
				                            $swap_class = "";
				                            if($swap_image && $hover_image = Mage::helper("ves_tempcp/framework")->getProductImage($_product->getId(), $swap_image_number, $this->getConfig("thumbWidth"), $this->getConfig("thumbHeight"))) {
				                                    $swap_class = "swap";
				                             } 
				                    ?>
									<div class="image <?php echo $swap_class; ?> product-image image-thumb">
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
											<?php 
											if($this->getConfig("enable_sale_icon")) {
				                                // Get the Special Price
				                                $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
				                                // Get the Special Price FROM date
				                                $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
				                                // Get the Special Price TO date
				                                $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
				                                // Get Current date
				                                $today =  time();
				                             
				                                if ($specialprice) {
				                                    if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)) {
			                            ?>
			                                    <span class="onsale"><span><?php echo $this->__("Sale");?></span></span>
			                            <?php  
			                                   	 }
			                                	}
			                           		}
			                            ?>
			                            	<?php
			                            	if($this->getConfig("enable_new_icon")) {
				                                $is_new = Mage::helper("ves_tempcp")->checkProductIsNew( $_product );
				                                
				                                if($is_new) { ?>
				                                <span class="new-icon"><span><?php echo $this->__("New");?></span></span>
				                                <?php

				                                }
				                            }
				                            ?>
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize( $this->getConfig("thumbWidth"), $this->getConfig("thumbHeight") ) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
										</a>
										<?php if($swap_class) { ?>
			                                <span class="hover-image">
			                                    <a class="img" href="<?php echo $_product->getProductUrl(); ?>"><img src="<?php echo $hover_image; ?>" width="<?php echo $list_image_width; ?>" height="<?php echo $list_image_height; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"></a>
			                                </span>
			                            <?php } ?>

										<?php if( $this->getConfig("show_pzoom") ) { ?>
										<?php
				                            $productId = $_product->getId();
				                            $_product = Mage::getModel('catalog/product')->load($productId);
				                        ?>
				                        <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(800);?>" class="colorbox product-zoom cboxElement" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><i class="icon-zoom-in"></i></a>
											<?php } ?>
									</div>
									<div class="product-info">
												<?php if( $this->getConfig('show_title') ) : ?>
												<h4 class="product-name">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php

														$product_name = $this->htmlEscape($_product->getName());
														echo $this->subString($product_name, $title_maxchar, "");

													 	?></a>
												</h4>
												<?php endif; ?>
												<?php if ( $this->getConfig('show_desc') ): ?>
												<div class="desc">
													<?php
														$product_short_desc = $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description');
														echo $this->subString($product_short_desc, $desc_maxchar, "");
													 ?>
												</div>
												<?php endif; ?>
												<?php if ( $this->getConfig('show_review') ): ?>
													<div class="review"><?php echo $this->getReviewsSummaryHtml($_product, 'short') ?></div>
												<?php endif; ?>
												<?php if($this->getConfig('show_price')): ?>
												<?php echo $this->getPriceHtml($_product, true) ?>
												<?php endif; ?>
											
												<div class="productcarousel-action">
													<?php if( $this->getConfig("show_addcart") ): ?>		                	
														<?php if($_product->isSaleable()): ?>
														<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
														<?php else: ?>
														<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
														<?php endif; ?>
													<?php endif; ?>
													<?php if( $this->getConfig("show_wc") ): ?>
															<div class="add-to-links">
																<div class="left">										
																	<a class="add-to-wishlist" href="<?php echo $this->helper('wishlist')->getAddUrl($_product);?>" title="<?php echo $this->__('Wishlist')?>"><?php echo $this->__('Wishlist')?></a>										
																</div>
																<div class="right">
																	<a class="add-to-compare" href="<?php echo $this->helper('catalog/product_compare')->getAddUrl($_product);?>" title="<?php echo $this->__('Compare')?>"><?php echo $this->__('Compare')?></a>
																</div>
															</div>
															<?php endif; ?>
													<div style="clear:both"></div>
												</div>
												<?php if ($quickview) { ?>
						                        <a class="ves-carousel-colorbox<?php echo $moduleId;?> ves-quickview" href="<?php echo Mage::helper("ves_tempcp")->getQuickviewURL( $_product->getProductUrl() ); ?>"><span class='fa fa-plus'></span><?php echo $this->__('Quick View'); ?></a>
						                    <?php } ?>
										</div>
   							    </div>
							</div>
							  
							<?php if( $cols==1 || $i%$cols == 0 || $i==count($tproducts) ) { ?>
							</div>
							<?php } ?>
							
						<?php } //endforeach; ?>
					</div>
				<?php } ?>
			
		</div>
	</div>
</div>
</div>
<?php if( $this->getConfig("show_pzoom") ) {  ?>
<script type="text/javascript">
<!--
jQuery(document).ready(function() {
	if(typeof(colorbox) != "undefined"){
		jQuery('.colorbox').colorbox({
			overlayClose: true,
			opacity: 0.5,
			rel: false,
			onLoad:function(){
				jQuery("#cboxNext").remove(0);
				jQuery("#cboxPrevious").remove(0);
				jQuery("#cboxCurrent").remove(0);
			}
		});
	}
	 
});
//-->
</script>
<?php } ?>

<script type="text/javascript">
jQuery('#productcarousel<?php echo $moduleId;?>').carousel({interval:<?php echo ( $auto_play_mode?$interval:'false') ;?>,auto:<?php echo $auto_play;?>,pause:'hover', cycle: true});
</script>


<?php if ($quickview) { ?>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".ves-carousel-colorbox<?php echo $moduleId;?>").colorbox({
                width: '<?php echo $popup_quickview_width; ?>', 
                height: '<?php echo $popup_quickview_height; ?>',
                overlayClose: true,
                opacity: 0.5,
                iframe: true, 
        });
        
    });
</script>
<?php } ?>