<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-post"><?php echo Mage::helper('ves_blog')->__('Posts Manager') ?></h3></td>
       
		<td style="width:15%;">
            <?php echo $this->getMassResizeButtonHtml() ?>
        </td>
		<td style="width:15%;">
            <?php echo $this->getMassRewritePostButtonHtml() ?>
        </td>
		 <td class="a-right">
            <?php echo $this->getAddNewButtonHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php   echo $this->getStoreSwitcherHtml() ?>
<div>
    <?php  echo $this->getGridHtml() ?>
</div>