<div id="appointment">
	<h1>Agende una cita</h1>

	<div class="form">

	<?php 
		//Get the customer data
		$customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();
		$customerName = Mage::getSingleton('customer/session')->getCustomer()->getName();
		$customerEmail = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
		
		if($customerId == ''){
	?>

		<div id="appointment-intro">
			<h2>PRUÉBATE UNA CAMISA ZIENTE</h2>
			<p>Alguna vez quiso probarse una camisa Ziente antes de comprarla? Ahora lo puede hacer. Programe una cita y pase por nuestro punto de venta para obtener una fácil y rápida experiencia de compra.</p>
			 
			<div class="button-center"><button class="button" onclick="location.href='customer/account/'">AGENDA</button></div>
		</div>

	<?php
		}else{
	?>

		<div class="form-confirmation">
			<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="confirmation-form">
				<div class="options">
					<p>Seleccione las siguientes opciones:</p>

					<?php $collection1 = Mage::getModel('appointments/locations')->getCollection(); ?>
					<p>Sede
					    <select name="location" id="locations" class="locations">
							<option value=" " selected="selected">Seleccione</option>
							<?php foreach($collection1 as $location) { ?>
					        	<option value="<?php echo $location->getId();?>"><?php echo $location->getName() . ' - ' . $location->getAddress();?></option>
					        <?php } ?>
					    </select>
					</p>

					<p>Fecha
						<select name="days" id="days" class="days"></select>
					</p>

				    <p>Hora
						<select name="hours" id="hours" class="hours"></select>
					</p>
				</div>

				<div class="confirmation">
					<p>Confirmación</p>			
					<div class="">
						<p>Nombre: <?php echo $customerName; ?></p>
						<p>Email:  <?php echo $customerEmail; ?></p>
						<p>Notas adicionales <textarea name="notes"></textarea></p>
					</div>
				</div>

				<div class="form-buttons">
					<input type="hidden" id="id" value="<?php echo $customerId; ?>">
					<input type="hidden" id="name" value="<?php echo $customerName; ?>">
					<input type="hidden" id="email" value="<?php echo $customerEmail; ?>">
					<button class="button" id="confirm-button" onclick="confirm()">Confirmar</button>
				</div>
			</form>
		</div>

	<?php
		}
	?>

	</div>
</div>


<script type="text/javascript">
	function confirm(){
   		var location = jQuery("#locations").val();
   		var day = jQuery("#days").val();
   		var hour = jQuery("#hours").val();

		if(location == ' '){
			alert("Por favor seleccione una sede");
			return false;
		}
		if(day == ' '){
			alert("Por favor seleccione un dia");
			return false;
		}
		if(hour == ' '){
			alert("Por favor seleccione una hora");
			return false;
		}
		

		//FALTA EL RESTO
		alert('LISTO');
	}	

	jQuery(document).ready(function (){
		jQuery('.locations').change(function() {
			var idLocation = jQuery("#locations").val();

			jQuery.ajax({
				url: '<?php echo Mage::getBaseUrl();?>ajax/days.php?id='+idLocation,
				context: document.body,
				success: function(data) {
					jQuery('#days').html(data);
				}
		  	});
		});

		jQuery('.days').change(function() {
			var idDay = jQuery("#days").val();

			jQuery.ajax({
				url: '<?php echo Mage::getBaseUrl();?>ajax/hours.php?id='+idDay,
				context: document.body,
				success: function(data) {
					jQuery('#hours').html(data);
				}
		  	});
		});
    });
</script>