<?php //$collection = Mage::getModel('appointments/location')->getCollection(); ?>

<div class="">

	<div style="width:450px; float:left; margin-left:30px;">
		<p>Seleccione:</p>

		<div class="">
			<?php $collection = Mage::getModel('appointments/appointments')->getCollection(); ?>

			<p>Sede
			    <select name="location" id="location" class="location">
					<option value=" " selected="selected">Seleccione</option>
					<?php foreach($collection as $location) { ?>
			        	<option value="<?php echo $location->getId();?>"><?php echo $location->getName() . ' - ' . $location->getAddress();?></option>
			        <?php } ?>
			    </select>
			</p>

			<p>Fecha
				<select name="day" id="day" class="day">
					<option value=" " selected="selected">Seleccione</option>
					<option value=" ">Mayo 26 de 2014</option>
					<option value=" ">Mayo 27 de 2014</option>
					<option value=" ">Mayo 28 de 2014</option>
					<option value=" ">Mayo 29 de 2014</option>
					<option value=" ">Mayo 30 de 2014</option>
			    </select>
			</p>

		    <p>Hora
				<select name="hours" id="hours" class="hours">
					<option value=" " selected="selected">Seleccione</option>
					<option value=" ">8:00 a 8:30</option>
					<option value=" ">8:30 a 9:00</option>
					<option value=" ">9:00 a 9:30</option>
					<option value=" ">9:30 a 10:00</option>
					<option value=" ">10:00 a 10:30</option>
					<option value=" ">10:30 a 11:00</option>
					<option value=" ">11:00 a 11:30</option>
					<option value=" ">11:30 a 12:00</option>
			    </select>
			</p>
		</div>
		<br />
	<!--
		<div class="form-buttons">
			 <button class="button" id="consult-button" onclick="">Continuar</button>
		</div>
	-->
	</div>



	<div style="width:450px; float:left; margin-left:30px;">
		<p>Confirmación</p>			
		<div class="">
			<p>Nombre: Mauricio Beltran</p>
			<p>Email: maobel@hotmail.com</p>
			<p>Notas adicionales <textarea name="notes"></textarea></p>
		</div>
		<br />
		<div class="form-buttons">
			 <button class="button" id="consult-button" onclick="">Confirmar</button>
		</div>
	</div>

</div>
